### ISSUE TITLE
https://pdap.io/ loads blank page until hard refresh on latest version of Chrome

### ISSUE THREAD

**Issue by katiemcculloch** [Police-Data-Accessibility-Project/PDAP.io#36] opened 2021-06-30 23:23 UTC
It's not an issue on Safari or Firefox. Josh said he's also seeing that behavior.

I can pick this issue up eventually (can't make an exact commitment atm), but also happy for someone else to fix if they can get to it sooner :)

**Comment by milespratt** [comment] 2021-07-11 15:01
I'm only able to reproduce intermittently in Chrome at the moment. @katiemcculloch @josh-chamberlain could you please share your version numbers of Chrome and the OS you're on?

Thanks!

**Comment by josh-chamberlain** [comment] 2021-07-13 20:21
- Chrome version `91.0.4472.114`
- Mac OS `10.15.7`

**Comment by josh-chamberlain** [comment] 2021-08-28 23:57
<img width="552" alt="Screen Shot 2021-08-28 at 7 57 42 PM" src="https://user-images.githubusercontent.com/30379833/131233853-71e44d58-de64-4b42-8805-674f543254c2.png">

**Comment by josh-chamberlain** [comment] 2021-09-29 15:14
<img width="1792" alt="Screen Shot 2021-09-29 at 11 14 06 AM" src="https://user-images.githubusercontent.com/30379833/135297914-dc4e1405-deac-4f3c-b51a-f35daa0f182f.png">

**Comment by josh-chamberlain** [comment] 2023-07-13 16:21
after getting a new laptop, I can no longer replicate this...I imagine some kind of chrome reinstall would fix this, but I'm closing because it only affects a small subset of people who loaded the website in the very early days. There are dozens of us!

**Closed by josh-chamberlain** 2023-07-13 16:21 UTC
Labels: bug, good first issue
